-- Setting up for unmatched codes

INSERT INTO `ICPC_Codes` (`id`, `title`) VALUES
('UNMCH1', 'MAP SOURCE CONCEPT CANNOT BE CLASSIFIED WITH AVAILABLE DATA'),
('UNMCH2', 'DESCENDANTS NOT EXHAUSTIVELY MAPPED | MAP SOURCE CONCEPT CANNOT BE CLASSIFIED WITH AVAILABLE DATA'),
('UNMCH3', 'SOURCE SNOMED CONCEPT IS AMBIGUOUS');


